services:
   hani:
    build:
      context: .
    ports:
      - "7681:7681"
    depends_on:
      - mcp-gateway
    env_file:
      - .env
    models:
      qwen3:
        model_var: GOOSE_MODEL
   mcp-gateway:
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=youtube_transcript

models:
 qwen3:
  # pre-pull the model when starting Docker Model Runner
  model: hf.co/unsloth/qwen3-30b-a3b-instruct-2507-gguf:q5_k_m
  context_size: 16355
    