services:
   space-goose-2:
    build:
      context: .
    ports:
      - "7681:7681"
    # depends_on:
    #   - goose-gateway-2
    env_file:
      - .env
    # models:
    #   local_model:
    #     model_var: GOOSE_MODEL
  #  goose-gateway-2:
  #   image: docker/mcp-gateway:latest
  #   use_api_socket: true
  #   command:
  #     - --transport=sse
  #     - --servers=github-official
#       - --secrets=/run/secrets/mcp_secret
#     secrets:
#       - mcp_secret

# secrets:
#   mcp_secret:
#     file: .env.mcp_gateway

# models:
#  local_model:
#   # pre-pull the model when starting Docker Model Runner
#   model: hf.co/unsloth/gpt-oss-20b-GGUF:q5_k_m
#   context_size: 16355
    