extensions:
  google-maps-sse:
    description: null
    enabled: true
    envs: {}
    name: google-maps-sse
    timeout: 15
    type: sse
    uri: http://localhost:8000/sse
GOOSE_MODE: auto
GOOSE_CLI_MIN_PRIORITY: 0.8
keyring: false
OPENAI_API_KEY: irrelevant
OPENAI_BASE_PATH: /engines/llama.cpp/v1/chat/completions
OPENAI_HOST: http://model-runner.docker.internal
OLLAMA_HOST: http://localhost:11434
