extensions:
  developer:
    display_name: null
    enabled: true
    name: developer
    timeout: null
    type: builtin
  mcp-gdrive-sse:
    description: null
    enabled: true
    envs: {}
    name: mcp-gdrive-sse
    timeout: 15
    type: sse
    uri: http://mcp-gdrive-sse:8000/sse
GOOSE_MODE: auto
GOOSE_CLI_MIN_PRIORITY: 0.8
keyring: false
OLLAMA_HOST: http://ollama:11434
